# Generated by Django 3.0.8 on 2020-07-23 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200723_1710'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_time'], 'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': '幻灯片', 'verbose_name_plural': '幻灯片'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['index'], 'verbose_name': '分类', 'verbose_name_plural': '分类'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '标签', 'verbose_name_plural': '标签'},
        ),
        migrations.AlterField(
            model_name='article',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='article_cover/%Y/%m/%d/', verbose_name='文章封面'),
        ),
    ]
