# Generated by Django 3.0.8 on 2020-07-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200723_1720'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['index'], 'verbose_name': '幻灯片', 'verbose_name_plural': '幻灯片'},
        ),
        migrations.AddField(
            model_name='banner',
            name='index',
            field=models.IntegerField(default=999),
        ),
    ]
