# Generated by Django 3.0.8 on 2020-07-24 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200723_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='link_url',
            new_name='link',
        ),
    ]
